#!/usr/bin/env bash
# Creates file, displays texts, deletes file and terminates
new_file="/var/run/myscript.pid"
echo $$ > "$new_file"

trap 'echo "I hate the kill command"; rm -rf "$new_file"; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -rf "$new_file"; exit' SIGQUIT

while ((1))
do
    echo "To infinity and beyond"
    sleep 2
done
