#!/usr/bin/env bash
# Bash scripts that creates a backup for /etc/hosts/ file and configures an ubuntu server to resolve the localhost to 127.0.0.2 and facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts /etc/hosts.backup

#Add custom entries to hosts file
echo "127.0.0.2 localhost" |sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" |sudo tee -a /etc/hosts > /dev/null

